deploy yml check

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,6 +10,17 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: SSH and Run Deploy Script
+
+
+	run: |
+          if [ -z "${{ secrets.OCI_HOST }}" ]; then
+            echo "OCI_HOST is EMPTY or NOT FOUND!"
+            exit 1
+          else
+            echo "OCI_HOST is detected."
+          fi
+
+	
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ secrets.OCI_HOST }}
